spring:
  swagger:
    enabled: true

dubbo:
  registry:
    protocol: zookeeper   # 注册中心支持的协议 包括 dubbo,multicast,zookeeper,redis 默认是dubbo
    # TODO 配置zookeeper地址
    address: 119.10.113.140:2181,119.10.113.140:2182,119.10.113.140:2183
    client: zkclient
  consumer:
    group: boot201

---
datasource:
  stsdb:
    driverClassName: com.mysql.jdbc.Driver
    # TODO 配置数据库地址
    url: jdbc:mysql://119.10.113.140:3306/stsdb?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: vcuser
    password: vcpass!@#QWE
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
     # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 100
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    #validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

# 604800是7天，1800是30分钟
mall:
  account:
    session:
      timeout: 604800
      pro:
        timeout: 60
    login:
      timeout: 604800
  website: http://wx.vcdianying.cn

wechat:
  h5:
  url: http://yh.vcdianying.cn
  appId: wxc76167d23de3813f
  appsecret: 9a9aa1c861dc3e8e7c8164a79af112d8